# Import numpy 

In [10]:
import numpy as np

In [108]:
list1D = [2,3,4,5,5,6,7,7] 
list2D = [[4,5,7],[30,34,90],[78,56,67],[776,78,66]] 

# Initializeing our arrays

In [109]:

nplist = np.array(list1D)
nplist2 = np.array(list2D)

print(type(list1D))
print('=====')
type(nplist)

<class 'list'>
=====


numpy.ndarray

# Dimension and shape

In [110]:
#number of diamensions 

print(nplist.ndim)
 
#shape

print(nplist.shape)
print("\n", nplist2.shape)

1
(8,)

 (4, 3)


# Changing the size of the items

In [111]:
print(nplist.dtype)

smallnp = np.array(list1D, dtype="int16")

print("\n", smallnp.dtype)

print("\n", nplist.nbytes)

print("\n", smallnp.nbytes)

int64

 int16

 64

 16


# Accessing items 

In [79]:
nplist

array([2, 3, 4, 5, 5, 6, 7, 7])

In [80]:
nplist[2]

4

In [81]:
nplist2

array([[  4,   5,   7],
       [ 30,  34,  90],
       [ 78,  56,  67],
       [776,  78,  66]])

In [82]:
nplist2[0][2]

7

# To change an item from the array

In [86]:
nplist[2] = 7
nplist

array([2, 3, 7, 5, 5, 6, 7, 7])

# Creating new arrays

In [2]:
#There are two functions that allow as to initialize array  of any 
#diamension

a = np.zeros(8)
b = np.zeros((2,3))
c = np.ones((2,3,2))
d = np.full((2,3), 10)

print("\n", a)
print("\n", b)
print("\n", c)
print("\n", d)


 [0. 0. 0. 0. 0. 0. 0. 0.]

 [[0. 0. 0.]
 [0. 0. 0.]]

 [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]

 [[10 10 10]
 [10 10 10]]


# generating an array with random numbers

In [104]:
#here we directly pass the diamensions of the metrix we want unlike the above case

r = np.random.rand(2,4)
r2 = np.random.rand(2,3,5)

print("\n", r)
print("\n", r2)


 [[0.07243638 0.60037866 0.09711244 0.23324624]
 [0.86471971 0.82243985 0.4394291  0.60038018]]

 [[[0.4969145  0.45871919 0.13733833 0.794646   0.28863117]
  [0.51838436 0.34578149 0.777566   0.86440324 0.3539286 ]
  [0.09071391 0.37925982 0.14165056 0.47662383 0.34240657]]

 [[0.54854771 0.48648584 0.36790448 0.87780187 0.86006742]
  [0.33237884 0.38684155 0.71064439 0.46139756 0.20024778]
  [0.38877617 0.98734332 0.77845875 0.69909746 0.46203057]]]


In [48]:
#TO generate interger numbers, first parameter is the range we want and second is the size of the metrix

intarray = np.random.randint(2,9, size=(4,5))

print(intarray)

#confirm that it is the right shape
print(intarray.shape)


[[2 3 7 4 7]
 [6 6 5 5 5]
 [2 8 2 8 7]
 [5 7 5 4 2]]
(4, 5)


In [51]:
#to repeat an array

arr = [[2,3,5,6]]

#must specify axis to repeat a multidiamensional array set it to 0.
np.repeat(arr,3, axis=0)


array([[2, 3, 5, 6],
       [2, 3, 5, 6],
       [2, 3, 5, 6]])

In [84]:

identity = np.ones((5,5))
zeros = np.zeros((3,3))
zeros[1,1] = 9

newarray = identity[1:4,1:4] = zeros

print(identity)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Mathematics with numpy

In [8]:
#BASIC MATHS OPERATIONS 

a = np.ones((4,4))

print(a)

#addition and subtraction 

#print(a[0] + 8)

print("\n", a + 6)
print("\n", a - 6)

#multiplication and division

print("\n", a * 9)
print("\n", a / 8)

#trignometry functions

print("\n", np.sin(a))
print("\n", np.cos(a))

#power functions

print("\n", a ** 4)

#

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 [[7. 7. 7. 7.]
 [7. 7. 7. 7.]
 [7. 7. 7. 7.]
 [7. 7. 7. 7.]]

 [[-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]]

 [[9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]]

 [[0.125 0.125 0.125 0.125]
 [0.125 0.125 0.125 0.125]
 [0.125 0.125 0.125 0.125]
 [0.125 0.125 0.125 0.125]]

 [[0.84147098 0.84147098 0.84147098 0.84147098]
 [0.84147098 0.84147098 0.84147098 0.84147098]
 [0.84147098 0.84147098 0.84147098 0.84147098]
 [0.84147098 0.84147098 0.84147098 0.84147098]]

 [[0.54030231 0.54030231 0.54030231 0.54030231]
 [0.54030231 0.54030231 0.54030231 0.54030231]
 [0.54030231 0.54030231 0.54030231 0.54030231]
 [0.54030231 0.54030231 0.54030231 0.54030231]]

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Linear algebra with numpy Metricies

In [126]:
a = np.full((2,4), 10)
b = np.full((4, 5), 9)

print("\n", a)
print("\n", b)

#To multiply the metricies we use the funtion matmul(matrix1, martix2)

c = np.matmul(a, b)
print("\n", c)



 [[10 10 10 10]
 [10 10 10 10]]

 [[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]

 [[360 360 360 360 360]
 [360 360 360 360 360]]


# Min and Max values of matrix

In [12]:
b = np.array([[3,4,5,6],[9,4,4,4,]])
print(b)
#to get min value
print("\n", np.min(b))

#max values
print("\n", np.max(b))

#min and max of each row if matrix is multidiamensional
print("\n", np.max(b, axis=1))

#to add all items in the matrix
print("\n", np.sum(b))


[[3 4 5 6]
 [9 4 4 4]]

 3

 9

 [6 9]

 39


# Reshaping a matrix

In [17]:
a = b.copy()

print(a.shape)
print("\n", a)

#You can change the shape of the matrix 
#When choosing a new size the existing items in the matrix must be able to create the new matrix.

new = a.reshape((1,8))
print("\n", new)
print("\n", new.shape)

(2, 4)

 [[3 4 5 6]
 [9 4 4 4]]

 [[3 4 5 6 9 4 4 4]]

 (1, 8)


# Reading matrix from a file

In [234]:
data = np.genfromtxt("matrixfile.txt", delimiter=',')

#all items will be casted to floats by default
print(data)

#cast to int
data2 = data.astype(int)
print("\n", data2)

data.shape

[[1. 2. 3. 4. 5. 6. 7. 8.]
 [1. 2. 3. 4. 5. 6. 7. 8.]
 [1. 2. 3. 4. 5. 6. 7. 8.]
 [1. 2. 3. 4. 5. 6. 7. 8.]
 [1. 2. 3. 4. 5. 6. 7. 8.]
 [1. 2. 3. 4. 5. 6. 7. 8.]
 [1. 2. 3. 4. 5. 6. 7. 8.]
 [1. 2. 3. 4. 5. 6. 7. 8.]]

 [[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


(8, 8)